// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | ImageSlice
  | QuoteSlice
  | TextSlice
  | ContactFormSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the article
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Publish Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date the article was published
   * - **API ID Path**: article.publishDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishDate: prismic.DateField;

  /**
   * Featured Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featuredImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredImage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type DevelopmentDocumentDataSlicesSlice = never;

/**
 * Item in *Development → Listing Images*
 */
export interface DevelopmentDocumentDataListingImagesItem {
  /**
   * Image field in *Development → Listing Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: development.listing_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Development documents
 */
interface DevelopmentDocumentData {
  /**
   * Name field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G Nexa Fields
   * - **API ID Path**: development.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Location Town field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G Pinhoe
   * - **API ID Path**: development.location_town
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_town: prismic.KeyTextField;

  /**
   * Location City field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G Exeter
   * - **API ID Path**: development.location_city
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_city: prismic.KeyTextField;

  /**
   * Location Postcode field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G EX2 8PA
   * - **API ID Path**: development.location_postcode
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location_postcode: prismic.KeyTextField;

  /**
   * Location County field in *Development*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: development.location_county
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_county: prismic.ContentRelationshipField<"taxonomy_location">;

  /**
   * Property Types field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development.property_types
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property_types: prismic.KeyTextField;

  /**
   * What3Words field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development.what_three_words
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  what_three_words: prismic.KeyTextField;

  /**
   * Development Size field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: development.development_size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  development_size: prismic.KeyTextField;

  /**
   * Development Status field in *Development*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: development.development_status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  development_status: prismic.ContentRelationshipField<"taxonomy_status">;

  /**
   * Prices From field in *Development*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: development.prices_from
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  prices_from: prismic.NumberField;

  /**
   * Slice Zone field in *Development*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: development.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DevelopmentDocumentDataSlicesSlice> /**
   * Meta Title field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: development.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Development*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: development.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Development*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: development.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Banner Image field in *Development*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: development.banner_image
   * - **Tab**: Images
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  banner_image: prismic.ImageField<never>;

  /**
   * Listing Images field in *Development*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: development.listing_images[]
   * - **Tab**: Images
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  listing_images: prismic.GroupField<
    Simplify<DevelopmentDocumentDataListingImagesItem>
  > /**
   * Brochure field in *Development*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: development.brochure
   * - **Tab**: Downloads
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  brochure: prismic.LinkField;
}

/**
 * Development document from Prismic
 *
 * - **API ID**: `development`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DevelopmentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DevelopmentDocumentData>,
    "development",
    Lang
  >;

/**
 * Item in *Home Page → Home Page Banner Images*
 */
export interface HomePageDocumentDataHomePageBannerImagesItem {
  /**
   * Image field in *Home Page → Home Page Banner Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.home_page_banner_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Banner Content field in *Home Page → Home Page Banner Images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.home_page_banner_images[].banner_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  banner_content: prismic.RichTextField;
}

type HomePageDocumentDataSlices2Slice =
  | StandardTextBlockSlice
  | DevelopmentShowcaseSlice
  | BlockContentSlice
  | InlineImagesSlice
  | LeadContentBlockSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Home Page Banner Images field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.home_page_banner_images[]
   * - **Tab**: Homepage Banner
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  home_page_banner_images: prismic.GroupField<
    Simplify<HomePageDocumentDataHomePageBannerImagesItem>
  > /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices2[]
   * - **Tab**: Homepage Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<HomePageDocumentDataSlices2Slice>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = MenuItemSlice;

type NavigationDocumentDataSlices1Slice = FooterMenuSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Header Link field in *Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.header_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  header_link: prismic.LinkField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice> /**
   * Footer Title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.footer_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  footer_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<NavigationDocumentDataSlices1Slice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImageSlice
  | QuoteSlice
  | TextSlice
  | ContactFormSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PropertyDocumentDataSlicesSlice = never;

/**
 * Content for Property documents
 */
interface PropertyDocumentData {
  /**
   * Development field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.development
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  development: prismic.ContentRelationshipField<"development">;

  /**
   * Title field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Bedrooms field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.bedrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  bedrooms: prismic.ContentRelationshipField<"taxonomy_number_of_bedrooms">;

  /**
   * Type field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  type: prismic.ContentRelationshipField<"taxonomy_house_type">;

  /**
   * Status field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  status: prismic.ContentRelationshipField<"taxonomy_status">;

  /**
   * Bathrooms field in *Property*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: property.bathrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bathrooms: prismic.SelectField<"1" | "2" | "3" | "4" | "5">;

  /**
   * Zero Bills field in *Property*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: property.zero_bills
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  zero_bills: prismic.BooleanField;

  /**
   * Price field in *Property*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: property.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Square Metres field in *Property*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: property.square_metres
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  square_metres: prismic.NumberField;

  /**
   * Slice Zone field in *Property*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: property.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PropertyDocumentDataSlicesSlice> /**
   * Meta Title field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: property.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: property.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Featured Image field in *Property*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: property.featured_image
   * - **Tab**: Images
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  featured_image: prismic.ImageField<never> /**
   * Map Location field in *Property*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: property.map_location
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */;
  map_location: prismic.GeoPointField;

  /**
   * Address Line 1 field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.address_line_1
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_1: prismic.KeyTextField;

  /**
   * Address Line 2 field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.address_line_2
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address_line_2: prismic.KeyTextField;

  /**
   * Town field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.town
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  town: prismic.KeyTextField;

  /**
   * Postcode field in *Property*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: property.postcode
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  postcode: prismic.KeyTextField;

  /**
   * Location Filter field in *Property*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: property.location_filter
   * - **Tab**: Location
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  location_filter: prismic.ContentRelationshipField<"taxonomy_location">;
}

/**
 * Property document from Prismic
 *
 * - **API ID**: `property`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropertyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PropertyDocumentData>,
    "property",
    Lang
  >;

type SearchDocumentDataSlicesSlice = never;

/**
 * Content for Search documents
 */
interface SearchDocumentData {
  /**
   * Title Lead field in *Search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search.title_lead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title field in *Search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Search*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: search.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SearchDocumentDataSlicesSlice> /**
   * Meta Title field in *Search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: search.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Search*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: search.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Search*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Search document from Prismic
 *
 * - **API ID**: `search`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SearchDocumentData>,
    "search",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Name field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Name of your blog (e.g. your name)
   * - **API ID Path**: settings.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short description of your blog
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Profile Picture field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.profilePicture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profilePicture: prismic.ImageField<never>;

  /**
   * Newsletter Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text above the sign up form
   * - **API ID Path**: settings.newsletterDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDescription: prismic.RichTextField;

  /**
   * Newsletter Disclaimer field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Small text below sign up form
   * - **API ID Path**: settings.newsletterDisclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsletterDisclaimer: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type SubMenuDocumentDataSlicesSlice = SubMenuItemSlice;

/**
 * Content for Sub Menu documents
 */
interface SubMenuDocumentData {
  /**
   * Sub Menu Header field in *Sub Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.sub_menu_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_menu_header: prismic.KeyTextField;

  /**
   * Slice Zone field in *Sub Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SubMenuDocumentDataSlicesSlice>;
}

/**
 * Sub Menu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubMenuDocumentData>,
    "sub_menu",
    Lang
  >;

/**
 * Content for [Taxonomy] - House Type documents
 */
interface TaxonomyHouseTypeDocumentData {
  /**
   * Name field in *[Taxonomy] - House Type*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G Detached
   * - **API ID Path**: taxonomy_house_type.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * [Taxonomy] - House Type document from Prismic
 *
 * - **API ID**: `taxonomy_house_type`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TaxonomyHouseTypeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TaxonomyHouseTypeDocumentData>,
    "taxonomy_house_type",
    Lang
  >;

/**
 * Content for [Taxonomy] - Location documents
 */
interface TaxonomyLocationDocumentData {
  /**
   * Name field in *[Taxonomy] - Location*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G Cornwall
   * - **API ID Path**: taxonomy_location.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * [Taxonomy] - Location document from Prismic
 *
 * - **API ID**: `taxonomy_location`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TaxonomyLocationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TaxonomyLocationDocumentData>,
    "taxonomy_location",
    Lang
  >;

/**
 * Content for [Taxonomy] - Number of Bedrooms documents
 */
interface TaxonomyNumberOfBedroomsDocumentData {
  /**
   * Number of Bedrooms field in *[Taxonomy] - Number of Bedrooms*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: taxonomy_number_of_bedrooms.number_of_bedrooms
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  number_of_bedrooms: prismic.NumberField;
}

/**
 * [Taxonomy] - Number of Bedrooms document from Prismic
 *
 * - **API ID**: `taxonomy_number_of_bedrooms`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TaxonomyNumberOfBedroomsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TaxonomyNumberOfBedroomsDocumentData>,
    "taxonomy_number_of_bedrooms",
    Lang
  >;

/**
 * Content for [Taxonomy] - Price Range documents
 */
interface TaxonomyPriceRangeDocumentData {
  /**
   * Price From field in *[Taxonomy] - Price Range*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: taxonomy_price_range.price_from
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_from: prismic.NumberField;

  /**
   * Price To field in *[Taxonomy] - Price Range*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: taxonomy_price_range.price_to
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price_to: prismic.NumberField;
}

/**
 * [Taxonomy] - Price Range document from Prismic
 *
 * - **API ID**: `taxonomy_price_range`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TaxonomyPriceRangeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TaxonomyPriceRangeDocumentData>,
    "taxonomy_price_range",
    Lang
  >;

/**
 * Content for [Taxonomy] - Status documents
 */
interface TaxonomyStatusDocumentData {
  /**
   * Name field in *[Taxonomy] - Status*
   *
   * - **Field Type**: Text
   * - **Placeholder**: E.G. Available
   * - **API ID Path**: taxonomy_status.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * [Taxonomy] - Status document from Prismic
 *
 * - **API ID**: `taxonomy_status`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TaxonomyStatusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TaxonomyStatusDocumentData>,
    "taxonomy_status",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | DevelopmentDocument
  | HomePageDocument
  | NavigationDocument
  | PageDocument
  | PropertyDocument
  | SearchDocument
  | SettingsDocument
  | SubMenuDocument
  | TaxonomyHouseTypeDocument
  | TaxonomyLocationDocument
  | TaxonomyNumberOfBedroomsDocument
  | TaxonomyPriceRangeDocument
  | TaxonomyStatusDocument;

/**
 * Item in *BlockContent → Testimonial → Primary → Testimonials*
 */
export interface BlockContentSliceTestimonialPrimaryTestimonialsItem {
  /**
   * Content field in *BlockContent → Testimonial → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.testimonial.primary.testimonials[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Author field in *BlockContent → Testimonial → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.testimonial.primary.testimonials[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Item in *BlockContent → Explore → Primary → Content Block*
 */
export interface BlockContentSliceExplorePrimaryContentBlockItem {
  /**
   * image field in *BlockContent → Explore → Primary → Content Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.content_block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *BlockContent → Explore → Primary → Content Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.content_block[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *BlockContent → Explore → Primary → Content Block*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.content_block[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *BlockContent → Explore → Primary → Content Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.content_block[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *BlockContent → Content List → Primary → Content Block*
 */
export interface BlockContentSliceContentListPrimaryContentBlockItem {
  /**
   * image field in *BlockContent → Content List → Primary → Content Block*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.content_block[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *BlockContent → Content List → Primary → Content Block*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.content_block[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *BlockContent → Content List → Primary → Content Block*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.content_block[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *BlockContent → Content List → Primary → Content Block*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.content_block[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *BlockContent → Search → Primary*
 */
export interface BlockContentSliceDefaultPrimary {
  /**
   * Title Lead field in *BlockContent → Search → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.default.primary.title_lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title field in *BlockContent → Search → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *BlockContent → Search → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Background Color field in *BlockContent → Search → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "White" | "VertoGreen",
    "filled"
  >;
}

/**
 * Search variation for BlockContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *BlockContent → Testimonial → Primary*
 */
export interface BlockContentSliceTestimonialPrimary {
  /**
   * Title Lead field in *BlockContent → Testimonial → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.testimonial.primary.title_lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title field in *BlockContent → Testimonial → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.testimonial.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Testimonials field in *BlockContent → Testimonial → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.testimonial.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<BlockContentSliceTestimonialPrimaryTestimonialsItem>
  >;

  /**
   * Background Color field in *BlockContent → Testimonial → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.testimonial.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "White" | "VertoGreen",
    "filled"
  >;
}

/**
 * Testimonial variation for BlockContent Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceTestimonial = prismic.SharedSliceVariation<
  "testimonial",
  Simplify<BlockContentSliceTestimonialPrimary>,
  never
>;

/**
 * Primary content in *BlockContent → Explore → Primary*
 */
export interface BlockContentSliceExplorePrimary {
  /**
   * Title Lead field in *BlockContent → Explore → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.title_lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title field in *BlockContent → Explore → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content Block field in *BlockContent → Explore → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.explore.primary.content_block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content_block: prismic.GroupField<
    Simplify<BlockContentSliceExplorePrimaryContentBlockItem>
  >;

  /**
   * Background Color field in *BlockContent → Explore → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.explore.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "VertoGreen",
    "filled"
  >;
}

/**
 * Explore variation for BlockContent Slice
 *
 * - **API ID**: `explore`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceExplore = prismic.SharedSliceVariation<
  "explore",
  Simplify<BlockContentSliceExplorePrimary>,
  never
>;

/**
 * Primary content in *BlockContent → With Image Lead → Primary*
 */
export interface BlockContentSliceWithImageLeadPrimary {
  /**
   * Image field in *BlockContent → With Image Lead → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.withImageLead.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Content field in *BlockContent → With Image Lead → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.withImageLead.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *BlockContent → With Image Lead → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.withImageLead.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Background Color field in *BlockContent → With Image Lead → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.withImageLead.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "White" | "VertoGreen",
    "filled"
  >;
}

/**
 * With Image Lead variation for BlockContent Slice
 *
 * - **API ID**: `withImageLead`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceWithImageLead = prismic.SharedSliceVariation<
  "withImageLead",
  Simplify<BlockContentSliceWithImageLeadPrimary>,
  never
>;

/**
 * Primary content in *BlockContent → Content List → Primary*
 */
export interface BlockContentSliceContentListPrimary {
  /**
   * Title Content field in *BlockContent → Content List → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.title_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_content: prismic.RichTextField;

  /**
   * Content Block field in *BlockContent → Content List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.contentList.primary.content_block[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content_block: prismic.GroupField<
    Simplify<BlockContentSliceContentListPrimaryContentBlockItem>
  >;

  /**
   * Background Color field in *BlockContent → Content List → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.contentList.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "White" | "VertoGreen",
    "filled"
  >;
}

/**
 * Content List variation for BlockContent Slice
 *
 * - **API ID**: `contentList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceContentList = prismic.SharedSliceVariation<
  "contentList",
  Simplify<BlockContentSliceContentListPrimary>,
  never
>;

/**
 * Primary content in *BlockContent → With Register Interest Form → Primary*
 */
export interface BlockContentSliceWithRegisterInterestFormPrimary {
  /**
   * Title field in *BlockContent → With Register Interest Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.withRegisterInterestForm.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *BlockContent → With Register Interest Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.withRegisterInterestForm.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Background Color field in *BlockContent → With Register Interest Form → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: VertoBlue
   * - **API ID Path**: block_content.withRegisterInterestForm.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_color: prismic.SelectField<
    "VertoBlue" | "VertoGrey" | "White" | "VertoGreen",
    "filled"
  >;
}

/**
 * With Register Interest Form variation for BlockContent Slice
 *
 * - **API ID**: `withRegisterInterestForm`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceWithRegisterInterestForm =
  prismic.SharedSliceVariation<
    "withRegisterInterestForm",
    Simplify<BlockContentSliceWithRegisterInterestFormPrimary>,
    never
  >;

/**
 * Slice variation for *BlockContent*
 */
type BlockContentSliceVariation =
  | BlockContentSliceDefault
  | BlockContentSliceTestimonial
  | BlockContentSliceExplore
  | BlockContentSliceWithImageLead
  | BlockContentSliceContentList
  | BlockContentSliceWithRegisterInterestForm;

/**
 * BlockContent Shared Slice
 *
 * - **API ID**: `block_content`
 * - **Description**: BlockContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSlice = prismic.SharedSlice<
  "block_content",
  BlockContentSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *DevelopmentShowcase → Default → Primary → Developments*
 */
export interface DevelopmentShowcaseSliceDefaultPrimaryDevelopmentsItem {
  /**
   * Development field in *DevelopmentShowcase → Default → Primary → Developments*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: development_showcase.default.primary.developments[].development
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  development: prismic.ContentRelationshipField<"development">;
}

/**
 * Primary content in *DevelopmentShowcase → Default → Primary*
 */
export interface DevelopmentShowcaseSliceDefaultPrimary {
  /**
   * Developments field in *DevelopmentShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: development_showcase.default.primary.developments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  developments: prismic.GroupField<
    Simplify<DevelopmentShowcaseSliceDefaultPrimaryDevelopmentsItem>
  >;
}

/**
 * Default variation for DevelopmentShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DevelopmentShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DevelopmentShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DevelopmentShowcase*
 */
type DevelopmentShowcaseSliceVariation = DevelopmentShowcaseSliceDefault;

/**
 * DevelopmentShowcase Shared Slice
 *
 * - **API ID**: `development_showcase`
 * - **Description**: DevelopmentShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DevelopmentShowcaseSlice = prismic.SharedSlice<
  "development_showcase",
  DevelopmentShowcaseSliceVariation
>;

/**
 * Item in *FooterMenu → Default → Primary → Links*
 */
export interface FooterMenuSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *FooterMenu → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *FooterMenu → Contact Details → Primary → Social Media*
 */
export interface FooterMenuSliceContactDetailsPrimarySocialMediaItem {
  /**
   * Link field in *FooterMenu → Contact Details → Primary → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.social_media[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *FooterMenu → Default → Primary*
 */
export interface FooterMenuSliceDefaultPrimary {
  /**
   * Title field in *FooterMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Links field in *FooterMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterMenuSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for FooterMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterMenuSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FooterMenu → Contact Details → Primary*
 */
export interface FooterMenuSliceContactDetailsPrimary {
  /**
   * Title field in *FooterMenu → Contact Details → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *FooterMenu → Contact Details → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Telephone field in *FooterMenu → Contact Details → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.telephone
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  telephone: prismic.NumberField;

  /**
   * Email field in *FooterMenu → Contact Details → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Social Media field in *FooterMenu → Contact Details → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.contactDetails.primary.social_media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media: prismic.GroupField<
    Simplify<FooterMenuSliceContactDetailsPrimarySocialMediaItem>
  >;
}

/**
 * Contact Details variation for FooterMenu Slice
 *
 * - **API ID**: `contactDetails`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMenuSliceContactDetails = prismic.SharedSliceVariation<
  "contactDetails",
  Simplify<FooterMenuSliceContactDetailsPrimary>,
  never
>;

/**
 * Slice variation for *FooterMenu*
 */
type FooterMenuSliceVariation =
  | FooterMenuSliceDefault
  | FooterMenuSliceContactDetails;

/**
 * FooterMenu Shared Slice
 *
 * - **API ID**: `footer_menu`
 * - **Description**: FooterMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterMenuSlice = prismic.SharedSlice<
  "footer_menu",
  FooterMenuSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Caption under the image
   * - **API ID Path**: image.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Wide → Primary*
 */
export interface ImageSliceWidePrimary {
  /**
   * Image field in *Image → Wide → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.wide.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Wide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Caption under the image
   * - **API ID Path**: image.wide.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Wide variation for Image Slice
 *
 * - **API ID**: `wide`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceWide = prismic.SharedSliceVariation<
  "wide",
  Simplify<ImageSliceWidePrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceWide;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *InlineImages → Default → Primary → Images*
 */
export interface InlineImagesSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *InlineImages → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inline_images.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *InlineImages → Default → Primary*
 */
export interface InlineImagesSliceDefaultPrimary {
  /**
   * Title field in *InlineImages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inline_images.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Images field in *InlineImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: inline_images.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<InlineImagesSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for InlineImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InlineImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InlineImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InlineImages*
 */
type InlineImagesSliceVariation = InlineImagesSliceDefault;

/**
 * InlineImages Shared Slice
 *
 * - **API ID**: `inline_images`
 * - **Description**: InlineImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InlineImagesSlice = prismic.SharedSlice<
  "inline_images",
  InlineImagesSliceVariation
>;

/**
 * Primary content in *LeadContentBlock → Default → Primary*
 */
export interface LeadContentBlockSliceDefaultPrimary {
  /**
   * Title Lead field in *LeadContentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_content_block.default.primary.title_lead
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_lead: prismic.KeyTextField;

  /**
   * Title field in *LeadContentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_content_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *LeadContentBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_content_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link field in *LeadContentBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: lead_content_block.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for LeadContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadContentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadContentBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LeadContentBlock*
 */
type LeadContentBlockSliceVariation = LeadContentBlockSliceDefault;

/**
 * LeadContentBlock Shared Slice
 *
 * - **API ID**: `lead_content_block`
 * - **Description**: LeadContentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadContentBlockSlice = prismic.SharedSlice<
  "lead_content_block",
  LeadContentBlockSliceVariation
>;

/**
 * Item in *MenuItem → With multiple Sub Menus → Primary → Sub Menus Group*
 */
export interface MenuItemSliceWithMultipleSubMenusPrimarySubMenusGroupItem {
  /**
   * Sub menu item in group field in *MenuItem → With multiple Sub Menus → Primary → Sub Menus Group*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withMultipleSubMenus.primary.sub_menus_group[].sub_menu_item_in_group
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sub_menu_item_in_group: prismic.ContentRelationshipField<"sub_menu">;
}

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Link Label field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MenuItem → Menu Item With SubMenu → Primary*
 */
export interface MenuItemSliceMenuItemWithSubMenuPrimary {
  /**
   * Link Label field in *MenuItem → Menu Item With SubMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.menuItemWithSubMenu.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Standard Sub Menu field in *MenuItem → Menu Item With SubMenu → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.menuItemWithSubMenu.primary.standard_sub_menu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  standard_sub_menu: prismic.ContentRelationshipField<"sub_menu">;
}

/**
 * Menu Item With SubMenu variation for MenuItem Slice
 *
 * - **API ID**: `menuItemWithSubMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceMenuItemWithSubMenu = prismic.SharedSliceVariation<
  "menuItemWithSubMenu",
  Simplify<MenuItemSliceMenuItemWithSubMenuPrimary>,
  never
>;

/**
 * Primary content in *MenuItem → With multiple Sub Menus → Primary*
 */
export interface MenuItemSliceWithMultipleSubMenusPrimary {
  /**
   * Link Label field in *MenuItem → With multiple Sub Menus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withMultipleSubMenus.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Sub Menus Group field in *MenuItem → With multiple Sub Menus → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.withMultipleSubMenus.primary.sub_menus_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sub_menus_group: prismic.GroupField<
    Simplify<MenuItemSliceWithMultipleSubMenusPrimarySubMenusGroupItem>
  >;
}

/**
 * With multiple Sub Menus variation for MenuItem Slice
 *
 * - **API ID**: `withMultipleSubMenus`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceWithMultipleSubMenus = prismic.SharedSliceVariation<
  "withMultipleSubMenus",
  Simplify<MenuItemSliceWithMultipleSubMenusPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation =
  | MenuItemSliceDefault
  | MenuItemSliceMenuItemWithSubMenu
  | MenuItemSliceWithMultipleSubMenus;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Quote without quotation marks
   * - **API ID Path**: quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.TitleField;

  /**
   * Source field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Source of the quote
   * - **API ID Path**: quote.default.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *StandardTextBlock → With Register Interest Form → Primary*
 */
export interface StandardTextBlockSliceDefaultPrimary {
  /**
   * Content field in *StandardTextBlock → With Register Interest Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * With Register Interest Form variation for StandardTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandardTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StandardTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StandardTextBlock*
 */
type StandardTextBlockSliceVariation = StandardTextBlockSliceDefault;

/**
 * StandardTextBlock Shared Slice
 *
 * - **API ID**: `standard_text_block`
 * - **Description**: StandardTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StandardTextBlockSlice = prismic.SharedSlice<
  "standard_text_block",
  StandardTextBlockSliceVariation
>;

/**
 * Primary content in *SubMenuItem → Default → Primary*
 */
export interface SubMenuItemSliceDefaultPrimary {
  /**
   * Link field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *SubMenuItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SubMenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubMenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SubMenuItem → With Development Reference → Primary*
 */
export interface SubMenuItemSliceWithDevelopmentReferencePrimary {
  /**
   * Development field in *SubMenuItem → With Development Reference → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.withDevelopmentReference.primary.development
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  development: prismic.ContentRelationshipField<"development">;

  /**
   * Show Developments of Status field in *SubMenuItem → With Development Reference → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_menu_item.withDevelopmentReference.primary.show_developments_of_status
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  show_developments_of_status: prismic.ContentRelationshipField<"taxonomy_status">;
}

/**
 * With Development Reference variation for SubMenuItem Slice
 *
 * - **API ID**: `withDevelopmentReference`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSliceWithDevelopmentReference =
  prismic.SharedSliceVariation<
    "withDevelopmentReference",
    Simplify<SubMenuItemSliceWithDevelopmentReferencePrimary>,
    never
  >;

/**
 * Slice variation for *SubMenuItem*
 */
type SubMenuItemSliceVariation =
  | SubMenuItemSliceDefault
  | SubMenuItemSliceWithDevelopmentReference;

/**
 * SubMenuItem Shared Slice
 *
 * - **API ID**: `sub_menu_item`
 * - **Description**: SubMenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubMenuItemSlice = prismic.SharedSlice<
  "sub_menu_item",
  SubMenuItemSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text with rich formatting
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      DevelopmentDocument,
      DevelopmentDocumentData,
      DevelopmentDocumentDataSlicesSlice,
      DevelopmentDocumentDataListingImagesItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataHomePageBannerImagesItem,
      HomePageDocumentDataSlices2Slice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocumentDataSlices1Slice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PropertyDocument,
      PropertyDocumentData,
      PropertyDocumentDataSlicesSlice,
      SearchDocument,
      SearchDocumentData,
      SearchDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SubMenuDocument,
      SubMenuDocumentData,
      SubMenuDocumentDataSlicesSlice,
      TaxonomyHouseTypeDocument,
      TaxonomyHouseTypeDocumentData,
      TaxonomyLocationDocument,
      TaxonomyLocationDocumentData,
      TaxonomyNumberOfBedroomsDocument,
      TaxonomyNumberOfBedroomsDocumentData,
      TaxonomyPriceRangeDocument,
      TaxonomyPriceRangeDocumentData,
      TaxonomyStatusDocument,
      TaxonomyStatusDocumentData,
      AllDocumentTypes,
      BlockContentSlice,
      BlockContentSliceDefaultPrimary,
      BlockContentSliceTestimonialPrimaryTestimonialsItem,
      BlockContentSliceTestimonialPrimary,
      BlockContentSliceExplorePrimaryContentBlockItem,
      BlockContentSliceExplorePrimary,
      BlockContentSliceWithImageLeadPrimary,
      BlockContentSliceContentListPrimaryContentBlockItem,
      BlockContentSliceContentListPrimary,
      BlockContentSliceWithRegisterInterestFormPrimary,
      BlockContentSliceVariation,
      BlockContentSliceDefault,
      BlockContentSliceTestimonial,
      BlockContentSliceExplore,
      BlockContentSliceWithImageLead,
      BlockContentSliceContentList,
      BlockContentSliceWithRegisterInterestForm,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      DevelopmentShowcaseSlice,
      DevelopmentShowcaseSliceDefaultPrimaryDevelopmentsItem,
      DevelopmentShowcaseSliceDefaultPrimary,
      DevelopmentShowcaseSliceVariation,
      DevelopmentShowcaseSliceDefault,
      FooterMenuSlice,
      FooterMenuSliceDefaultPrimaryLinksItem,
      FooterMenuSliceDefaultPrimary,
      FooterMenuSliceContactDetailsPrimarySocialMediaItem,
      FooterMenuSliceContactDetailsPrimary,
      FooterMenuSliceVariation,
      FooterMenuSliceDefault,
      FooterMenuSliceContactDetails,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceWidePrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceWide,
      InlineImagesSlice,
      InlineImagesSliceDefaultPrimaryImagesItem,
      InlineImagesSliceDefaultPrimary,
      InlineImagesSliceVariation,
      InlineImagesSliceDefault,
      LeadContentBlockSlice,
      LeadContentBlockSliceDefaultPrimary,
      LeadContentBlockSliceVariation,
      LeadContentBlockSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceMenuItemWithSubMenuPrimary,
      MenuItemSliceWithMultipleSubMenusPrimarySubMenusGroupItem,
      MenuItemSliceWithMultipleSubMenusPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      MenuItemSliceMenuItemWithSubMenu,
      MenuItemSliceWithMultipleSubMenus,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      StandardTextBlockSlice,
      StandardTextBlockSliceDefaultPrimary,
      StandardTextBlockSliceVariation,
      StandardTextBlockSliceDefault,
      SubMenuItemSlice,
      SubMenuItemSliceDefaultPrimary,
      SubMenuItemSliceWithDevelopmentReferencePrimary,
      SubMenuItemSliceVariation,
      SubMenuItemSliceDefault,
      SubMenuItemSliceWithDevelopmentReference,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
    };
  }
}
