// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_content: dynamic(() => import("./AccordionContent")),
  articles_listing: dynamic(() => import("./ArticlesListing")),
  block_content: dynamic(() => import("./BlockContent")),
  check_list: dynamic(() => import("./CheckList")),
  company_contact_details: dynamic(() => import("./CompanyContactDetails")),
  contact_form: dynamic(() => import("./ContactForm")),
  development_showcase: dynamic(() => import("./DevelopmentShowcase")),
  energy_comparison: dynamic(() => import("./StatisticComparisonCards")),
  footer_menu: dynamic(() => import("./FooterMenu")),
  fullimage_block: dynamic(() => import("./FullimageBlock")),
  image: dynamic(() => import("./Image")),
  image_grid: dynamic(() => import("./ImageGrid")),
  inline_images: dynamic(() => import("./InlineImages")),
  lead_content_block: dynamic(() => import("./LeadContentBlock")),
  map_location: dynamic(() => import("./MapLocation")),
  menu_item: dynamic(() => import("./MenuItem")),
  property_grid: dynamic(() => import("./PropertyGrid")),
  quote: dynamic(() => import("./Quote")),
  rich_content_block: dynamic(() => import("./RichContentBlock")),
  split_content_block: dynamic(() => import("./SplitContentBlock")),
  standard_text_block: dynamic(() => import("./StandardTextBlock")),
  steps: dynamic(() => import("./Steps")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text: dynamic(() => import("./Text")),
  timeline: dynamic(() => import("./Timeline")),
  typology_layout: dynamic(() => import("./TypologyLayout")),
  video: dynamic(() => import("./Video")),
  zero_bills_homes_slider: dynamic(() => import("./ZeroBillsHomesSlider")),
};
