// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  block_content: dynamic(() => import("./BlockContent")),
  contact_form: dynamic(() => import("./ContactForm")),
  development_showcase: dynamic(() => import("./DevelopmentShowcase")),
  footer_menu: dynamic(() => import("./FooterMenu")),
  image: dynamic(() => import("./Image")),
  image_grid: dynamic(() => import("./ImageGrid")),
  inline_images: dynamic(() => import("./InlineImages")),
  lead_content_block: dynamic(() => import("./LeadContentBlock")),
  menu_item: dynamic(() => import("./MenuItem")),
  quote: dynamic(() => import("./Quote")),
  standard_text_block: dynamic(() => import("./StandardTextBlock")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  text: dynamic(() => import("./Text")),
};
